### ISSUE TITLE
Routes from London Kings Cross going South involve many turns

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-setup#34]
Reproducible example: https://www.cyclestreets.net/journey/79719873/

As shown there and in the image below there are quite a few turns in each route option. From a user perspective the easiest option is to get straight onto the A201 which takes you straight there on reasonably quiet / protected infrastructure. The dotted red line represents the 'route 1' option from Google that is best from the perspective of minimising turns and maximising continuity.

![image](https://user-images.githubusercontent.com/1825120/152675059-8cc16b5c-dd7a-4ac5-abc2-1259fcc03e4d.png)

Source: https://www.google.com/maps/dir/Kings+Cross,+London/SE11+4JP,+London/@51.5118702,-0.1440914,13z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x48761b10c73c4dcd:0x616f11fed05d6bb9!2m2!1d-0.1245845!2d51.5347488!1m5!1m1!1s0x4876049745fd7d11:0x8a34ecfec0841e5c!2m2!1d-0.1065995!2d51.4893899!3e1

Not sure this is the right place for people to submit feedback in an open forum on routing but hope this is useful feedback nonetheless.

**Comment by mvl22** [comment]
Moved to /feedback/15739/ .

**Comment by mvl22** [comment]
That first third of the suggested route is significantly unsuitable for a lot of users. The bit you mark coming from the station, which is not part of the official cycle network (unlike our recommendation)is often not great as it gets the traffic emerging from Euston Road. The Farringdon section adjacent to the undercut can be pretty hairy as it's too narrow for the volume of vehicles.

Once the segregated infrastructure starts after that, things are fine. But it's not easy to get to that from King's Cross without using the historical Camden route that weaves through past the old post office, and which has *way* more turns. The latter two thirds are then fine as I say. (TfL has done great work in gradually extending up the Blackfriars route more and more north, but it starts too late from King's Cross.)

In terms of turns, I'd say there are remarkably few turns in our route for what is a route through central London, which is notoriously difficult to route for. We correctly find the long section along Judd which is very often traffic-free in my experience.
