### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/cyclestreets-setup#5]
Aim to get rid of all cyclestreets.cnf writing - currently setup by import and live deployment.

The main thing they set is:

 query-cache
 utf8

The rest of the application should do what they are currently trying to do. But the utf8 setting should remain as really that should be system wide.

**Comment by mvl22** [comment]
https://dev.mysql.com/doc/refman/5.6/en/query-cache-configuration.html

**Comment by si-the-pie** [comment]
5d548cbabe9fbbd8d670e9c393e84fc6f8dd3578 and its offspring addressed the utf8 aspect of this ticket.

**Comment by mvl22** [comment]
> query-cache

This was removed in MySQL 8 so must not be present now, otherwise MySQL does not start.

**Comment by mvl22** [comment]
Issue superseded in #22.
